version: "3.8"

services:
  chore_tracker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DISPLAY=:99
    
    # command: >
    #   sh -c "rm -f /tmp/.X99-lock && Xvfb :99 -screen 0 1024x768x16 & \
    #   while ! xdpyinfo -display :99 > /dev/null 2>&1; do sleep 1; done; \
    #   python chore_tracker.py"